services:  # Servisler (Konteynerler) dizimi
  # 1-servis: Maǵlıwmatlar bazası (PostgreSQL)
  db:
    image: postgres:15-alpine  # Rásmiy, jeńil PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # Maǵlıwmatlardı saqlaw (Persistency)
    env_file:
      - .env  # Barlıq o'zgeriwshilerdi usı fayldan júkle!
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  # 2-servis: Biziń Django joybarımız
  web:
    build: .  # Dockerfile-di usı papkadan izle hám qur
    # command: python manage.py runserver 0.0.0.0:8000  # Islep shıǵıw ushın
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app  # Kodtı jańalaw (Hot-reload) ushın
      - static_volume:/app/staticfiles  # Jańa volume!
    ports:
      - "8000:8000"  # Brauzerden kiriw ushın
    depends_on:
      - db  # Baza iske túspesten, Django iske túspewi kerek
    env_file:
      - .env  # Barlıq o'zgeriwshilerdi usı fayldan júkle!

volumes:
  postgres_data:  # Baza maǵlıwmatları saqlanatuǵın orın
  static_volume:  # Dizimnen o'tkeremiz