# Generated by Django 6.0.2 on 2026-03-29 12:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
                ('slug', models.SlugField(unique=True, verbose_name='category URL slug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='warehouse.category', verbose_name='father category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('slug', models.SlugField(unique=True, verbose_name='product URL slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='product description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='product price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='product discount price')),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='product stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='product is active')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_image/', verbose_name='product image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.category', verbose_name='category')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_price__lt', models.F('price'))), name='discount_price_must_be_less_than_price')],
            },
        ),
    ]
